version: "3.9"

services:
  backend:
    build: ../backend
    env_file:
      - ./../backend/.env
    ports:
      - "8000:8000"
    depends_on: []
    networks:
      - network-matrixhub

  frontend:
    build: ../frontend
    env_file:
      - ./../frontend/.env.local
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - network-matrixhub

networks:
  network-matrixhub:
    driver: bridge
